import type { Question } from "@/modules/curriculum/types";

const source = { type: "original", name: "Learning Minds", rightsStatus: "Learning Minds original; demo use permitted" } as const;
const q = (question: Omit<Question, "version" | "versionId" | "source">): Question => ({ ...question, version: 1, versionId: `${question.id}-v1`, source });
export const questions: Question[] = [
  q({ id:"lm-math-001",topicId:"linear",objectiveIds:["linear-solve"],difficulty:"foundation",marks:1,type:"multiple_choice",prompt:"Solve 3x + 5 = 20.",options:[{id:"a",label:"x = 3"},{id:"b",label:"x = 5"},{id:"c",label:"x = 8"},{id:"d",label:"x = 15"}],answer:{correctOption:"b"},correctAnswer:"x = 5",explanation:"Subtract 5, then divide 15 by 3.",calculatorAllowed:false,estimatedMinutes:1 }),
  q({ id:"lm-math-002",topicId:"linear",objectiveIds:["linear-solve"],difficulty:"standard",marks:2,type:"numerical",prompt:"Solve 4(x − 2) = 20. Enter x.",answer:{value:7,tolerance:0},correctAnswer:"7",explanation:"Divide by 4 to get x − 2 = 5, then add 2.",calculatorAllowed:false,estimatedMinutes:2 }),
  q({ id:"lm-math-003",topicId:"linear",objectiveIds:["linear-model"],difficulty:"standard",marks:2,type:"short_text",prompt:"Write an equation for: three more than twice a number x is 17.",answer:{acceptedAnswers:["2x+3=17","3+2x=17"]},correctAnswer:"2x + 3 = 17",explanation:"Twice x is 2x; three more gives 2x + 3.",calculatorAllowed:false,estimatedMinutes:2 }),
  q({ id:"lm-math-004",topicId:"linear",objectiveIds:["linear-solve"],difficulty:"foundation",marks:1,type:"true_false",prompt:"The solution of 5x − 10 = 0 is x = 2.",answer:{correctBoolean:true},correctAnswer:"True",explanation:"5(2) − 10 = 0.",calculatorAllowed:false,estimatedMinutes:1 }),
  q({ id:"lm-math-005",topicId:"simultaneous",objectiveIds:["sim-eliminate"],difficulty:"standard",marks:1,type:"multiple_choice",prompt:"Given x + y = 9 and x − y = 3, what is x?",options:[{id:"a",label:"3"},{id:"b",label:"5"},{id:"c",label:"6"},{id:"d",label:"12"}],answer:{correctOption:"c"},correctAnswer:"6",explanation:"Add the equations: 2x = 12, so x = 6.",calculatorAllowed:false,estimatedMinutes:2 }),
  q({ id:"lm-math-006",topicId:"simultaneous",objectiveIds:["sim-eliminate"],difficulty:"standard",marks:2,type:"numerical",prompt:"Solve x + y = 11 and x − y = 5. Enter y.",answer:{value:3,tolerance:0},correctAnswer:"3",explanation:"Subtract the second equation from the first: 2y = 6.",calculatorAllowed:false,estimatedMinutes:2 }),
  q({ id:"lm-math-007",topicId:"simultaneous",objectiveIds:["sim-substitute"],difficulty:"challenge",marks:3,type:"structured_response",prompt:"Solve y = 2x + 1 and 3x + y = 16. Give x and y.",answer:{criteria:[{id:"x",description:"Correct x value",marks:1,acceptedAnswers:["x=3","3"]},{id:"y",description:"Correct y value",marks:1,acceptedAnswers:["y=7","7"]},{id:"method",description:"Valid substitution shown",marks:1}],manualReview:true},correctAnswer:"x = 3, y = 7",explanation:"Substitute y: 3x + 2x + 1 = 16, so x = 3 and y = 7.",calculatorAllowed:false,estimatedMinutes:4 }),
  q({ id:"lm-math-008",topicId:"quadratic",objectiveIds:["quad-factor"],difficulty:"foundation",marks:1,type:"multiple_choice",prompt:"Which is the factorisation of x² + 7x + 12?",options:[{id:"a",label:"(x + 3)(x + 4)"},{id:"b",label:"(x − 3)(x − 4)"},{id:"c",label:"(x + 2)(x + 6)"},{id:"d",label:"(x − 2)(x − 6)"}],answer:{correctOption:"a"},correctAnswer:"(x + 3)(x + 4)",explanation:"3 × 4 = 12 and 3 + 4 = 7.",calculatorAllowed:false,estimatedMinutes:1 }),
  q({ id:"lm-math-009",topicId:"quadratic",objectiveIds:["quad-factor"],difficulty:"standard",marks:2,type:"numerical",prompt:"One root of x² − 9x + 20 = 0 is 4. Enter the other root.",answer:{value:5,tolerance:0},correctAnswer:"5",explanation:"The equation factorises as (x − 4)(x − 5) = 0.",calculatorAllowed:false,estimatedMinutes:2 }),
  q({ id:"lm-math-010",topicId:"quadratic",objectiveIds:["quad-roots"],difficulty:"standard",marks:1,type:"true_false",prompt:"The equation x² + 4x + 5 = 0 has two real roots.",answer:{correctBoolean:false},correctAnswer:"False",explanation:"Its discriminant is 16 − 20 = −4, so it has no real roots.",calculatorAllowed:false,estimatedMinutes:2 }),
  q({ id:"lm-math-011",topicId:"quadratic",objectiveIds:["quad-formula"],difficulty:"challenge",marks:3,type:"structured_response",prompt:"Use the quadratic formula to solve 2x² − 3x − 2 = 0. Show substitution and give both roots.",answer:{criteria:[{id:"sub",description:"Correct substitution",marks:1},{id:"root1",description:"Root x = 2",marks:1,acceptedAnswers:["2","x=2"]},{id:"root2",description:"Root x = −0.5",marks:1,acceptedAnswers:["-0.5","x=-0.5","-1/2"]}],manualReview:true},correctAnswer:"x = 2 or x = −1/2",explanation:"x = (3 ± √25)/4 = (3 ± 5)/4.",calculatorAllowed:true,estimatedMinutes:5 }),
  q({ id:"lm-math-012",topicId:"quadratic",objectiveIds:["quad-factor"],difficulty:"standard",marks:2,type:"short_text",prompt:"State both roots of (x − 6)(x + 2) = 0.",answer:{acceptedAnswers:["6,-2","-2,6","x=6,x=-2","x=-2,x=6"]},correctAnswer:"x = 6 and x = −2",explanation:"Set each factor equal to zero.",calculatorAllowed:false,estimatedMinutes:2 }),
  q({ id:"lm-math-013",topicId:"pythagoras",objectiveIds:["pyth-identify"],difficulty:"foundation",marks:1,type:"multiple_choice",prompt:"In a right-angled triangle, which side is the hypotenuse?",options:[{id:"a",label:"The shortest side"},{id:"b",label:"The side opposite the right angle"},{id:"c",label:"The vertical side"},{id:"d",label:"The side adjacent to any angle"}],answer:{correctOption:"b"},correctAnswer:"The side opposite the right angle",explanation:"It is also the longest side.",calculatorAllowed:false,estimatedMinutes:1 }),
  q({ id:"lm-math-014",topicId:"pythagoras",objectiveIds:["pyth-calculate"],difficulty:"foundation",marks:2,type:"numerical",prompt:"A right triangle has shorter sides 6 cm and 8 cm. Enter the hypotenuse in cm.",answer:{value:10,tolerance:0},correctAnswer:"10 cm",explanation:"√(6² + 8²) = √100 = 10.",calculatorAllowed:true,estimatedMinutes:2 }),
  q({ id:"lm-math-015",topicId:"pythagoras",objectiveIds:["pyth-calculate"],difficulty:"standard",marks:2,type:"numerical",prompt:"A right triangle has hypotenuse 13 m and one shorter side 5 m. Find the other side in m.",answer:{value:12,tolerance:0},correctAnswer:"12 m",explanation:"√(13² − 5²) = √144 = 12.",calculatorAllowed:true,estimatedMinutes:2 }),
  q({ id:"lm-math-016",topicId:"trigonometry",objectiveIds:["trig-ratios"],difficulty:"foundation",marks:1,type:"multiple_choice",prompt:"Which ratio equals opposite ÷ hypotenuse?",options:[{id:"a",label:"sine"},{id:"b",label:"cosine"},{id:"c",label:"tangent"},{id:"d",label:"Pythagoras"}],answer:{correctOption:"a"},correctAnswer:"sine",explanation:"SOH means sine = opposite/hypotenuse.",calculatorAllowed:false,estimatedMinutes:1 }),
  q({ id:"lm-math-017",topicId:"trigonometry",objectiveIds:["trig-side"],difficulty:"standard",marks:2,type:"numerical",prompt:"A right triangle has hypotenuse 12 cm and an angle of 30°. Find the side opposite the angle in cm.",answer:{value:6,tolerance:0.05},correctAnswer:"6 cm",explanation:"opposite = 12 sin 30° = 6.",calculatorAllowed:true,estimatedMinutes:3 }),
  q({ id:"lm-math-018",topicId:"trigonometry",objectiveIds:["trig-angle"],difficulty:"standard",marks:2,type:"numerical",prompt:"Opposite = 5 and adjacent = 5 in a right triangle. Find the acute angle in degrees.",answer:{value:45,tolerance:0.1},correctAnswer:"45°",explanation:"tan θ = 1, so θ = tan⁻¹(1) = 45°.",calculatorAllowed:true,estimatedMinutes:3 }),
  q({ id:"lm-math-019",topicId:"trigonometry",objectiveIds:["trig-identify"],difficulty:"foundation",marks:1,type:"short_text",prompt:"What is the name of the longest side in a right-angled triangle?",answer:{acceptedAnswers:["hypotenuse","the hypotenuse"]},correctAnswer:"Hypotenuse",explanation:"It lies opposite the right angle.",calculatorAllowed:false,estimatedMinutes:1 }),
  q({ id:"lm-math-020",topicId:"trigonometry",objectiveIds:["trig-side","trig-ratios"],difficulty:"challenge",marks:3,type:"structured_response",prompt:"A ladder makes a 65° angle with level ground and reaches 4.5 m up a wall. Calculate the ladder length to 2 decimal places. Show the ratio used.",answer:{criteria:[{id:"ratio",description:"Uses sin 65° = 4.5/L",marks:1},{id:"method",description:"Rearranges L = 4.5/sin 65°",marks:1},{id:"answer",description:"L = 4.97 m",marks:1,acceptedAnswers:["4.97","4.97m","4.97 m"]}],manualReview:true},correctAnswer:"4.97 m",explanation:"sin 65° = opposite/hypotenuse = 4.5/L, so L = 4.5/sin 65°.",calculatorAllowed:true,estimatedMinutes:4 }),
  q({ id:"lm-math-021",topicId:"pythagoras",objectiveIds:["pyth-calculate"],difficulty:"standard",marks:1,type:"multiple_choice",prompt:"Which calculation finds a missing shorter side when c is the hypotenuse?",options:[{id:"a",label:"√(c² + a²)"},{id:"b",label:"c² − a²"},{id:"c",label:"√(c² − a²)"},{id:"d",label:"c − a"}],answer:{correctOption:"c"},correctAnswer:"√(c² − a²)",explanation:"Rearrange a² + b² = c², then take the square root.",calculatorAllowed:false,estimatedMinutes:1 })
];
export const getQuestion = (id: string) => questions.find((item) => item.id === id);
