import Link from "next/link";
import { curriculum, units } from "@/modules/curriculum/catalogue";
const destinations = [
 {title:"Revision notes",desc:"Clear explanations, worked examples and checkpoints.",href:"/app/revise/notes",number:"01"},
 {title:"Topical questions",desc:"Build a focused practice set from the original question bank.",href:"/app/revise/questions",number:"02"},
 {title:"Past papers",desc:"Authorised resources and the Learning Minds original mini mock.",href:"/app/revise/past-papers",number:"03"},
 {title:"Strengths & weaknesses",desc:"Use your attempt evidence to choose what to study next.",href:"/app/progress",number:"04"}
];
export const metadata={title:"Revision Hub"};
export default function RevisePage(){return <div><section className="diagram-grid border-b border-ink-950/10 bg-canvas"><div className="mx-auto max-w-6xl px-5 py-10 sm:px-9 lg:px-12 lg:py-14"><p className="text-xs font-bold tracking-[.2em] text-leaf-700 uppercase">Revision hub</p><div className="mt-5 grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><h1 className="font-display text-5xl leading-[.95] sm:text-7xl">Mathematics</h1><p className="mt-5 font-semibold">{curriculum.level} <span className="mx-2 text-ink-500">/</span> {curriculum.name}</p><p className="mt-2 text-sm text-ink-500">{curriculum.scope}</p></div><Link href="/app/exams/new" className="inline-flex min-h-12 items-center justify-center rounded-md bg-ink-950 px-6 font-bold text-paper">Create timed exam →</Link></div><dl className="mt-10 grid max-w-2xl grid-cols-3 border-t border-ink-950/15 pt-5"><div><dt className="text-xs text-ink-500">Overall progress</dt><dd className="mt-1 font-display text-2xl">Not started</dd></div><div><dt className="text-xs text-ink-500">Topics studied</dt><dd className="mt-1 font-display text-2xl">0 / 6</dd></div><div><dt className="text-xs text-ink-500">Recent activity</dt><dd className="mt-1 font-display text-2xl">—</dd></div></dl></div></section><div className="mx-auto max-w-6xl px-5 py-10 sm:px-9 lg:px-12"><div className="divide-y divide-ink-950/10 border-y border-ink-950/10">{destinations.map(d=><Link key={d.title} href={d.href} className="group grid gap-3 py-7 sm:grid-cols-[3rem_1fr_auto] sm:items-center"><span className="font-display text-2xl text-sky-500">{d.number}</span><span><strong className="text-xl">{d.title}</strong><span className="mt-1 block text-sm text-ink-500">{d.desc}</span></span><span className="text-2xl transition-transform group-hover:translate-x-1">→</span></Link>)}</div><section className="mt-12"><p className="text-xs font-bold tracking-[.18em] text-ink-500 uppercase">Curriculum path</p><div className="mt-5 grid gap-6 md:grid-cols-2">{units.map(unit=><div key={unit.id} className="border-l-2 border-sky-500 pl-5"><h2 className="font-display text-2xl">{unit.title}</h2><p className="mt-2 text-sm text-ink-500">{unit.topics.length} topics · {unit.topics.flatMap(t=>t.objectives).length} objectives</p></div>)}</div></section></div></div>}
