"use client";
import { useMemo, useState, useTransition } from "react"; import { completeOnboarding } from "@/modules/onboarding/actions";
import { curricula, grades, learningGoals, subjects } from "@/modules/onboarding/catalogue"; import type { OnboardingState, UserRole } from "@/modules/onboarding/types";
const initial: OnboardingState = { role: null, displayName: "", preferredLanguage: "en", country: "MZ", curriculumId: null, gradeId: null, subjectIds: [], learningGoalMinutes: 20 };
const roleOptions: { id: UserRole; title: string; copy: string; symbol: string }[] = [{ id: "student", title: "Student", copy: "Learn, revise, practise and track your progress.", symbol: "01" }, { id: "teacher", title: "Teacher", copy: "Guide students, create learning activities and understand progress.", symbol: "02" }];
const optionClass = (selected: boolean) => `group relative w-full rounded-lg border p-5 text-left transition duration-normal ${selected ? "border-leaf-700 bg-leaf-100/55 shadow-[inset_0_0_0_1px_#245d45] -translate-y-0.5" : "border-ink-950/15 bg-paper hover:-translate-y-0.5 hover:border-ink-950/40"}`;
export function OnboardingFlow() {
  const [data, setData] = useState(initial); const [step, setStep] = useState(0); const [error, setError] = useState(""); const [pending, startTransition] = useTransition();
  const teacher = data.role === "teacher"; const steps = teacher ? ["Role", "About you", "Curriculum", "Subjects", "Ready"] : ["Role", "About you", "Country", "Curriculum", "Level", "Subjects", "Goal", "Ready"];
  const availableGrades = useMemo(() => grades.filter((grade) => grade.curriculumId === data.curriculumId), [data.curriculumId]);
  const valid = step === 0 ? !!data.role : step === 1 ? data.displayName.trim().length >= 2 : teacher ? step === 2 ? !!data.curriculumId && !!data.gradeId : step === 3 ? data.subjectIds.length > 0 : true : step === 2 ? !!data.country : step === 3 ? !!data.curriculumId : step === 4 ? !!data.gradeId : step === 5 ? data.subjectIds.length > 0 : true;
  const chooseCurriculum = (id: OnboardingState["curriculumId"]) => { const first = grades.find((g) => g.curriculumId === id); setData({ ...data, curriculumId: id, gradeId: teacher ? first?.id ?? null : null }); };
  const toggleSubject = (id: OnboardingState["subjectIds"][number]) => setData({ ...data, subjectIds: data.subjectIds.includes(id) ? data.subjectIds.filter((value) => value !== id) : [...data.subjectIds, id] });
  const finish = () => startTransition(async () => { const result = await completeOnboarding(data); if (result?.error) setError(result.error); });
  return <div className="min-h-screen bg-paper lg:grid lg:grid-cols-[20rem_1fr]">
    <aside className="diagram-grid border-b border-ink-950/10 bg-canvas px-5 py-5 lg:min-h-screen lg:border-r lg:border-b-0 lg:px-8 lg:py-9"><a href="/" className="font-display text-xl font-semibold">Learning Minds</a><p className="mt-10 hidden text-sm font-bold text-ink-500 lg:block">Your beginning</p><ol className="mt-5 flex gap-2 lg:grid lg:gap-0">{steps.map((label, index) => <li key={label} className={`flex items-center gap-3 border-l-2 py-2 pl-3 text-sm transition lg:py-3 ${index === step ? "border-leaf-700 font-bold text-ink-950" : index < step ? "border-leaf-100 text-leaf-700" : "border-transparent text-ink-500"}`}><span className="hidden font-display text-base lg:inline">{String(index + 1).padStart(2, "0")}</span><span className={index === step ? "inline" : "hidden lg:inline"}>{label}</span></li>)}</ol><div className="mt-4 h-1 overflow-hidden bg-ink-950/10 lg:mt-10"><div className="h-full bg-leaf-700 transition-all duration-normal" style={{ width: `${((step + 1) / steps.length) * 100}%` }}/></div></aside>
    <main className="flex min-h-[calc(100vh-7rem)] items-center px-5 py-10 sm:px-10 lg:px-16 xl:px-24"><div key={`${teacher}-${step}`} className="animate-step-in mx-auto w-full max-w-3xl">
      {step === 0 && <Step eyebrow="Your place here" title="How will you use Learning Minds?" copy="Choose the space that best fits the work you want to do."><div className="grid gap-3 sm:grid-cols-2">{roleOptions.map((role) => <button key={role.id} className={optionClass(data.role === role.id)} aria-pressed={data.role === role.id} onClick={() => { setData({ ...initial, role: role.id }); }}><span className="font-display text-xl text-ink-500">{role.symbol}</span><h2 className="mt-10 font-display text-3xl">{role.title}</h2><p className="mt-3 leading-6 text-ink-500">{role.copy}</p></button>)}</div></Step>}
      {step === 1 && <Step eyebrow="About you" title="Let’s make Learning Minds yours." copy="Tell us what to call you and which language feels most natural."><label className="block text-sm font-bold">Display name<input autoFocus value={data.displayName} onChange={(e) => setData({ ...data, displayName: e.target.value })} className="mt-2 min-h-13 w-full border-0 border-b border-ink-950/25 bg-transparent text-xl outline-none focus:border-leaf-700" /></label><fieldset className="mt-8"><legend className="text-sm font-bold">Preferred language</legend><div className="mt-3 flex gap-3">{[["en", "English"], ["pt", "Português"]].map(([id, label]) => <button key={id} type="button" onClick={() => setData({ ...data, preferredLanguage: id as "en" | "pt" })} aria-pressed={data.preferredLanguage === id} className={optionClass(data.preferredLanguage === id)}>{label}</button>)}</div></fieldset></Step>}
      {!teacher && step === 2 && <Step eyebrow="Your context" title="Where are you studying?" copy="This helps us present the right learning pathways."><button className={optionClass(true)} aria-pressed="true"><span className="text-xs font-bold tracking-wider text-leaf-700 uppercase">Supported now</span><h2 className="mt-8 font-display text-3xl">Mozambique</h2><p className="mt-2 text-ink-500">Curriculum choices tailored to your study context.</p></button></Step>}
      {((teacher && step === 2) || (!teacher && step === 3)) && <Step eyebrow="Curriculum" title="What are you studying?" copy={teacher ? "Choose the curriculum you teach. You can expand this later." : "Select the pathway that shapes your current studies."}><div className="grid gap-3">{curricula.map((item) => <button key={item.id} className={optionClass(data.curriculumId === item.id)} aria-pressed={data.curriculumId === item.id} onClick={() => chooseCurriculum(item.id)}><span className="text-xs font-bold tracking-wider text-ink-500 uppercase">Curriculum</span><h2 className="mt-5 font-display text-2xl">{item.name}</h2><p className="mt-2 text-ink-500">{item.description}</p></button>)}</div>{teacher && data.curriculumId && <div className="mt-5 flex gap-2">{availableGrades.map((grade) => <button key={grade.id} onClick={() => setData({ ...data, gradeId: grade.id })} className={`border px-4 py-2 text-sm ${data.gradeId === grade.id ? "border-leaf-700 bg-leaf-100" : "border-ink-950/15"}`}>{grade.name}</button>)}</div>}</Step>}
      {!teacher && step === 4 && <Step eyebrow="Your level" title="Where are you on the path?" copy="Choose your current grade or qualification."><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{availableGrades.map((grade) => <button key={grade.id} className={optionClass(data.gradeId === grade.id)} aria-pressed={data.gradeId === grade.id} onClick={() => setData({ ...data, gradeId: grade.id })}><span className="font-display text-2xl">{grade.name}</span></button>)}</div></Step>}
      {((teacher && step === 3) || (!teacher && step === 5)) && <Step eyebrow={teacher ? "Your teaching" : "Your interests"} title={teacher ? "What subjects do you teach?" : "What do you want to learn?"} copy="Choose one or more. Each subject keeps its own quiet visual identity."><div className="grid gap-3 sm:grid-cols-2">{subjects.map((subject) => <button key={subject.id} className={`${optionClass(data.subjectIds.includes(subject.id))} subject-${subject.accent}`} aria-pressed={data.subjectIds.includes(subject.id)} onClick={() => toggleSubject(subject.id)}><div aria-hidden className="subject-visual"><span className="subject-mark absolute left-5 top-5 block size-3 rounded-full"/></div><h2 className="mt-5 text-2xl font-bold">{subject.name}</h2><p className="mt-2 text-sm text-ink-500">{data.subjectIds.includes(subject.id) ? "Selected" : "Select subject"}</p></button>)}</div></Step>}
      {!teacher && step === 6 && <Step eyebrow="Daily rhythm" title="How much time would you like to learn each day?" copy="Build a rhythm that feels achievable. You can change this later."><div className="relative grid gap-3 sm:grid-cols-4">{learningGoals.map((goal) => <button key={goal.minutes} className="flex min-h-28 w-full flex-col justify-between rounded-lg border border-ink-950/15 bg-paper p-4 text-left transition hover:-translate-y-0.5" aria-pressed={data.learningGoalMinutes === goal.minutes} onClick={() => setData({ ...data, learningGoalMinutes: goal.minutes })}><span className="font-display text-2xl">{goal.label}</span><span className={`rounded-full px-3 py-1 text-sm font-bold ${data.learningGoalMinutes === goal.minutes ? "bg-leaf-700 text-white" : "bg-canvas text-ink-500"}`}>{goal.minutes} min/day</span></button>)}</div></Step>}
      {step === steps.length - 1 && <Step eyebrow="Ready" title={`You’re ready, ${data.displayName}.`} copy={teacher ? "Your workspace is prepared around what you teach." : "Your first Learning Minds space is shaped around you."}><div className="grid gap-px bg-ink-950/10 sm:grid-cols-2">{[
        { label: "Curriculum", value: curricula.find((v) => v.id === data.curriculumId)?.name },
        { label: "Level", value: grades.find((v) => v.id === data.gradeId)?.name },
        { label: teacher ? "Subjects taught" : "Subjects", value: data.subjectIds.map((id) => subjects.find((v) => v.id === id)?.name).join(", ") },
        ...(!teacher ? [{ label: "Daily goal", value: `${data.learningGoalMinutes} minutes` }] : []),
      ].map(({ label, value }) => <div key={label} className="bg-paper p-5"><p className="text-xs font-bold tracking-wider text-ink-500 uppercase">{label}</p><p className="mt-2 font-display text-xl">{value}</p></div>)}</div>{error && <p role="alert" className="mt-5 text-sm text-coral-500">{error}</p>}</Step>}
      <div className="mt-9 flex items-center justify-between"><button onClick={() => setStep(Math.max(0, step - 1))} disabled={step === 0 || pending} className="min-h-11 px-2 text-sm font-bold text-ink-500 disabled:invisible">← Back</button>{step === steps.length - 1 ? <button onClick={finish} disabled={pending} className="min-h-12 rounded-md bg-leaf-700 px-6 font-bold text-white disabled:opacity-60">{pending ? "Saving your choices…" : teacher ? "Enter Teacher Workspace" : "Enter Learning Minds"}</button> : <button onClick={() => setStep(step + 1)} disabled={!valid} className="min-h-12 rounded-md bg-leaf-700 px-7 font-bold text-white transition disabled:cursor-not-allowed disabled:opacity-35">Continue →</button>}</div>
    </div></main>
  </div>;
}
function Step({ eyebrow, title, copy, children }: { eyebrow: string; title: string; copy: string; children: React.ReactNode }) { return <section><p className="text-sm font-bold text-leaf-700">{eyebrow}</p><h1 className="mt-3 max-w-2xl text-4xl font-bold leading-[1.05] tracking-tight sm:text-5xl">{title}</h1><p className="mt-4 mb-9 max-w-xl leading-7 text-ink-500">{copy}</p>{children}</section>; }
