-- Phase 3: canonical curriculum, versioned content, assessment evidence and mastery.
create type public.publication_status as enum ('draft','published','archived');
create type public.question_type as enum ('multiple_choice','true_false','numerical','short_text','structured_response');
create type public.source_type as enum ('original','authorised_past_paper','teacher_created');
create type public.session_status as enum ('created','in_progress','submitted','expired');

create table public.curricula (id text primary key, country_code text not null, name text not null, description text, is_demo_subset boolean not null default false, created_at timestamptz not null default now());
create table public.courses_or_levels (id text primary key, curriculum_id text not null references public.curricula(id), name text not null, sort_order smallint not null);
create table public.subjects (id text primary key, course_or_level_id text not null references public.courses_or_levels(id), name text not null, slug text not null, accent text, unique(course_or_level_id,slug));
create table public.units (id text primary key, subject_id text not null references public.subjects(id), name text not null, sort_order smallint not null);
create table public.topics (id text primary key, unit_id text not null references public.units(id), name text not null, slug text not null unique, summary text, sort_order smallint not null);
create table public.learning_objectives (id text primary key, topic_id text not null references public.topics(id), statement text not null, sort_order smallint not null);

create table public.content_items (id text primary key, topic_id text not null references public.topics(id), content_type text not null check(content_type in ('revision_note','resource')), current_version_id uuid, created_at timestamptz not null default now());
create table public.content_versions (id uuid primary key default gen_random_uuid(), content_item_id text not null references public.content_items(id), version integer not null check(version>0), title text not null, blocks jsonb not null check(jsonb_typeof(blocks)='array'), status public.publication_status not null default 'draft', source_type public.source_type not null default 'original', source_metadata jsonb not null default '{}', rights_status text not null, published_at timestamptz, unique(content_item_id,version));
alter table public.content_items add constraint content_current_version_fk foreign key(current_version_id) references public.content_versions(id);

create table public.questions (id text primary key, subject_id text not null references public.subjects(id), topic_id text not null references public.topics(id), current_version_id uuid, created_at timestamptz not null default now());
create table public.question_versions (id uuid primary key default gen_random_uuid(), question_id text not null references public.questions(id), version integer not null check(version>0), difficulty text not null check(difficulty in ('foundation','standard','challenge')), marks smallint not null check(marks>0), question_type public.question_type not null, prompt jsonb not null, answer_configuration jsonb not null, explanation jsonb not null default '{}', calculator_allowed boolean not null default false, estimated_seconds integer, status public.publication_status not null default 'draft', source_type public.source_type not null default 'original', source_metadata jsonb not null default '{}', rights_status text not null, published_at timestamptz, unique(question_id,version));
alter table public.questions add constraint question_current_version_fk foreign key(current_version_id) references public.question_versions(id);
create table public.question_objectives (question_id text not null references public.questions(id), learning_objective_id text not null references public.learning_objectives(id), primary key(question_id,learning_objective_id));
create table public.mark_schemes (id uuid primary key default gen_random_uuid(), question_version_id uuid not null references public.question_versions(id), version integer not null check(version>0), criteria jsonb not null, status public.publication_status not null default 'draft', published_at timestamptz, unique(question_version_id,version));

create table public.practice_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, subject_id text not null references public.subjects(id), status public.session_status not null default 'created', started_at timestamptz, completed_at timestamptz, created_at timestamptz not null default now());
create table public.practice_session_questions (practice_session_id uuid not null references public.practice_sessions(id) on delete cascade, question_version_id uuid not null references public.question_versions(id), position smallint not null, primary key(practice_session_id,position), unique(practice_session_id,question_version_id));
create table public.exam_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, subject_id text not null references public.subjects(id), title text not null default 'Timed exam', status public.session_status not null default 'created', duration_seconds integer not null check(duration_seconds>0), calculator_allowed boolean not null default false, started_at timestamptz, submitted_at timestamptz, created_at timestamptz not null default now());
create table public.exam_session_questions (exam_session_id uuid not null references public.exam_sessions(id) on delete cascade, question_version_id uuid not null references public.question_versions(id), position smallint not null, flagged boolean not null default false, primary key(exam_session_id,position), unique(exam_session_id,question_version_id));
create table public.attempts (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, practice_session_id uuid references public.practice_sessions(id), exam_session_id uuid references public.exam_sessions(id), started_at timestamptz, submitted_at timestamptz not null default now(), duration_seconds integer, check(num_nonnulls(practice_session_id,exam_session_id)<=1));
create table public.attempt_answers (id uuid primary key default gen_random_uuid(), attempt_id uuid not null references public.attempts(id) on delete cascade, question_version_id uuid not null references public.question_versions(id), submitted_answer jsonb not null, marks_awarded numeric(6,2) not null check(marks_awarded>=0), maximum_marks numeric(6,2) not null check(maximum_marks>0), correctness text not null check(correctness in ('correct','incorrect','partial','self_review')), marked_at timestamptz not null default now(), unique(attempt_id,question_version_id));
create table public.learner_objective_states (user_id uuid not null references auth.users(id) on delete cascade, learning_objective_id text not null references public.learning_objectives(id), mastery_score smallint not null check(mastery_score between 0 and 100), evidence_count integer not null default 0, calculation_version text not null default 'recent-weighted-v1', calculated_at timestamptz not null default now(), primary key(user_id,learning_objective_id));

-- Published canonical data is readable; user evidence is strictly owner-scoped.
do $$ declare t text; begin foreach t in array array['curricula','courses_or_levels','subjects','units','topics','learning_objectives','content_items','content_versions','questions','question_versions','question_objectives','mark_schemes','practice_sessions','practice_session_questions','exam_sessions','exam_session_questions','attempts','attempt_answers','learner_objective_states'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
create policy "read curricula" on public.curricula for select to authenticated using(true);
create policy "read levels" on public.courses_or_levels for select to authenticated using(true);
create policy "read subjects" on public.subjects for select to authenticated using(true);
create policy "read units" on public.units for select to authenticated using(true);
create policy "read topics" on public.topics for select to authenticated using(true);
create policy "read objectives" on public.learning_objectives for select to authenticated using(true);
create policy "read published content items" on public.content_items for select to authenticated using(exists(select 1 from public.content_versions v where v.id=current_version_id and v.status='published'));
create policy "read published content versions" on public.content_versions for select to authenticated using(status='published');
create policy "read published questions" on public.questions for select to authenticated using(exists(select 1 from public.question_versions v where v.id=current_version_id and v.status='published'));
create policy "read published question versions" on public.question_versions for select to authenticated using(status='published');
create policy "read published question objectives" on public.question_objectives for select to authenticated using(exists(select 1 from public.questions q join public.question_versions v on v.id=q.current_version_id where q.id=question_id and v.status='published'));
create policy "read published mark schemes" on public.mark_schemes for select to authenticated using(status='published');
create policy "own practice sessions" on public.practice_sessions for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "own practice questions" on public.practice_session_questions for all to authenticated using(exists(select 1 from public.practice_sessions s where s.id=practice_session_id and s.user_id=auth.uid())) with check(exists(select 1 from public.practice_sessions s where s.id=practice_session_id and s.user_id=auth.uid()));
create policy "own exams" on public.exam_sessions for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "own exam questions" on public.exam_session_questions for all to authenticated using(exists(select 1 from public.exam_sessions s where s.id=exam_session_id and s.user_id=auth.uid())) with check(exists(select 1 from public.exam_sessions s where s.id=exam_session_id and s.user_id=auth.uid()));
create policy "own attempts" on public.attempts for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "own answers" on public.attempt_answers for all to authenticated using(exists(select 1 from public.attempts a where a.id=attempt_id and a.user_id=auth.uid())) with check(exists(select 1 from public.attempts a where a.id=attempt_id and a.user_id=auth.uid()));
create policy "own mastery" on public.learner_objective_states for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);

insert into public.curricula values ('moz-national-demo','MZ','Mozambique National Curriculum','Competition demo subset; not a complete official curriculum.',true,now());
insert into public.courses_or_levels values ('mz-10','moz-national-demo','10ª Classe',10);
insert into public.subjects values ('mz-10-mathematics','mz-10','Mathematics','mathematics','#4f8fa8');
insert into public.units values ('algebra','mz-10-mathematics','Algebra',1),('geometry-trig','mz-10-mathematics','Geometry & Trigonometry',2);
insert into public.topics values ('linear','algebra','Linear equations','linear-equations','Solve equations with one unknown.',1),('simultaneous','algebra','Simultaneous equations','simultaneous-equations','Solve two equations together.',2),('quadratic','algebra','Quadratic equations','quadratic-equations','Solve and interpret equations with a squared term.',3),('pythagoras','geometry-trig','Pythagoras','pythagoras','Relate sides of a right triangle.',4),('trigonometry','geometry-trig','Trigonometric ratios','trigonometric-ratios','Use sine, cosine and tangent.',5),('trig-applications','geometry-trig','Applications of trigonometry','applications-of-trigonometry','Model heights and distances.',6);
insert into public.learning_objectives values ('linear-solve','linear','Solve linear equations with one unknown',1),('linear-model','linear','Model a context using a linear equation',2),('sim-eliminate','simultaneous','Solve simultaneous equations by elimination',1),('sim-substitute','simultaneous','Solve simultaneous equations by substitution',2),('quad-factor','quadratic','Solve quadratic equations by factorisation',1),('quad-formula','quadratic','Solve quadratic equations using the quadratic formula',2),('quad-roots','quadratic','Interpret roots and the discriminant',3),('pyth-identify','pythagoras','Identify the hypotenuse',1),('pyth-calculate','pythagoras','Calculate an unknown side using Pythagoras',2),('trig-identify','trigonometry','Identify opposite, adjacent and hypotenuse',1),('trig-ratios','trigonometry','Choose and use sine, cosine and tangent',2),('trig-side','trigonometry','Calculate unknown sides',3),('trig-angle','trigonometry','Calculate unknown angles',4),('trig-model','trig-applications','Model a practical problem with a right triangle',1);

grant select on public.curricula,public.courses_or_levels,public.subjects,public.units,public.topics,public.learning_objectives,public.content_items,public.content_versions,public.questions,public.question_versions,public.question_objectives,public.mark_schemes to authenticated;
grant select,insert,update on public.practice_sessions,public.practice_session_questions,public.exam_sessions,public.exam_session_questions,public.attempts,public.attempt_answers,public.learner_objective_states to authenticated;
